export const MOBILE_OPEN = 'MOBILE_OPEN'
export const MOBILE_CLOSE = 'MOBILE_CLOSE'
export const GET_PROPERTIES_BEGIN = "GET_PROPERTIES_BEGIN"
export const GET_PROPERTIES_SUCCESS = "GET_PROPERTIES_SUCCESS"
export const GET_PROPERTIES_ERROR = "GET_PROPERTIES_ERROR"
export const GET_SINGLE_PROPERTY_BEGIN = "GET_SINGLE_PROPERTY_BEGIN"
export const GET_SINGLE_PROPERTY_SUCCESS = "GET_SINGLE_PROPERTY_SUCCESS"
export const GET_SINGLE_PROPERTY_ERROR = "GET_SINGLE_PROPERTY_ERROR"